<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.history.js'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/kmb.mco.history.css'); ?>
<div class="row">
    <div class="col-md-12">
	<a tabindex="900" href="<?= $this->url('mcollective', [ 'action' => 'history', 'agent' => null ], [], true) ?>" class="btn btn-info"><i class="glyphicon glyphicon-chevron-left"></i><?= $this->translate('Back') ?></a>
    </div>
    </div>
    <hr />
<?php if(isset($actionid)): ?>
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
	  <span class="glyphicon glyphicon-tasks"></span><span class="panel-break"></span><?= sprintf($this->translate("Execution summary for action %s"),$actionid); ?>
      </div>
      <div class="panel-body">
	  <blockquote>
	      <?= sprintf($this->translatePlural("%d response received","%d responses received",sizeof($logs)),sizeof($logs)) ?> <?php if($errorcount != 0): ?> <?= sprintf($this->translatePlural("(with <span style=\"color:red;\">%d</span> error)","(with <span style=\"color:red;\">%d</span> errors)",$errorcount),$errorcount); ?>
	      <?php endif ?>.
	  </blockquote>
	  <?php if(is_array($logs)): ?>
          <!-- <?php error_log(print_r($logs,true)); ?> -->
	  <ul>
	      <?php foreach($logs as $hostname => $log): ?>
	      <table class="table">
	          <tr>
	              <th colspan="2"> <?= $hostname ?></th>
	          </tr>
	          <?php foreach( $log as $line): ?>
                  <?php $results = json_decode($line['result']); ?>
                  <?php error_log(print_r($line,true)); ?>
	          <tr id="line_<?= str_replace('.','_',$hostname) ?>_<?= $line['requestid'] ?>" class="result_line" data-target="#<?= str_replace('.','_',$hostname) ?>_<?= $line['requestid']; ?>">
	              <td><?= $line['agent'] ?>::<?= $line['action'];?></td>
                      <td align="right">
		          <?php if($line['statuscode'] == 0): ?>
		          <span class="label label-success">Success</span>
		          <?php else: ?>
		          <span class="label label-danger">Error</span>
		          <?php endif ?>
                      </td>
                      <div id="<?= str_replace('.','_',$hostname) ?>_<?= $line['requestid']; ?>_title" style="display:none">
                          <?= sprintf($this->translate("Result for action %s"),$line['agent']. "::".$line['action']); ?>
                      </div>
	              <div id="<?= str_replace('.','_',$hostname) ?>_<?= $line['requestid']; ?>" class="result_detail">
	                  <?php $dataResult = json_decode($line['result']); ?>
                          <?php if($dataResult) : ?>
	                  <?php foreach(get_object_vars($dataResult) as $name => $value): ?>
                          <?php if ($value === "") { continue; } ?>
	                  <span class="label label-default result-mco"><?= $name ?></span>
                          <?php if( is_string($value)) : ?>
	                  <pre><?= trim($value) ?></pre>
                          <?php else : ?>
                          <pre><?= json_encode($value) ?></pre>
                          <?php endif ?>
	                  <?php endforeach ?>
                          <?php endif ?>
	              </div>
              	  </tr>
	          <?php endforeach ?>
              </table>
	      <?php endforeach ?>
	  </ul>
	  <?php else: ?>
	  <table class="table">
	      <thead>
	          <th colspan="2"> <?= $logs->getHostname(); ?></th>
	      </thead>
              <tbody>
	          <tr>
	              <td><?= $logs->getAgent() ?>::<?= $logs->getAction();?></td><td align="right">
	                  <?php if($logs->getStatusCode == 0): ?>
	                  <span class="label label-success">Success</span>
	                  <?php else: ?>
	                  <span class="label label-danger">Danger</span>
	                  <?php endif ?></td>
	          </tr>
              </tbody>
	  </table>
	  <div id="<?= str_replace('.','_',$hostname) ?>_<?= $logs->getRequestId(); ?>" class="result_detail">
	  </div>
	  <?php endif ?>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
      <div id="details" data-spy="affix" data-offset-top="0">
          <h2><?= $this->translate("Help"); ?></h2>
          <blockquote>
	      <?= $this->translate("Click on action name to see action output"); ?>
          </blockquote>
          <div id="result">
          </div>
      </div>
  </div>
</div>
<?php else: ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.logs.js'); ?>
<div class="panel-heading">
    <span class="glyphicon glyphicon-tasks"></span><span class="panel-break"></span>Historique des actions mcollectives
</div>
<div class="panel-body">
    <?php echo $this->datatable('historyDatatable')->renderHtml(); ?>
</div>


<?php endif ?>
