<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.logs.js'); ?>
<div class="panel-heading">
  <span class="glyphicon glyphicon-tasks"></span><span class="panel-break"></span>Historique des actions mcollectives
</div>
<div class="panel-body">
  <ul>
    <?php foreach($lines as $mcolog):?>
    <li><a href="<?php echo $this->url('mcollective_history', ['id' => $mcolog->getActionid() ], [], true) ?>" ><?= $mcolog->getActionid() ?> </a> ( <?= $mcolog->getFullName() ?>) </li>
    <? endforeach ?>
  </ul>
</div>
<?php echo $this->datatable('historyDatatable')->renderHtml(); ?>
