<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.metadatas.js'); ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/bootstrap-iconpicker.min.js'); ?>
<?php $this->inlineScript()->prependFile($this->basePath() . '/js/iconset/iconset-glyphicon.min.js'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/kmb.mco.css'); ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-iconpicker.min.css'); ?>
<div class="row">
  <?php if( $agent != null): ?>
  <form class="form-horizontal" role="form" action="<?php echo $this->url('mcollective_metadatas_update', ['action' => 'metadataUpdate'], [], true) ?>" method="POST" id="metadataForm">
    <div class="row">
      <div>
		<div id="actions" class="editable-actions pull-right" style="display: none">
	  <div>&nbsp;</div>
	  <button class="btn btn-default" tabindex="110" type="reset"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('Cancel') ?></button>
	  <button class="btn btn-primary" tabindex="112" type="submit"><i class="glyphicon glyphicon-ok"></i> <?php echo $this->translate('Save') ?></button>
	</div>

	<div class="form-group">
	  <div class="col-md-6" >
	    <label for="agentDescription"><?= sprintf($this->translate('%s agent description'), $agent) ?></label>
	    <input type="text" class="form-control editable" data-target="#actions" id="agentDesc" name="agentDesc" value="<?= $agentDetail->getDescription() ?>" placeholder="Description.."/>
	    <input type="hidden" name="agent" value="<?= $agent ?>"/>
	  </div>
	  <div>&nbsp</div>
	</div>
	<div>
	<a tabindex="900" href="<?= $this->url('mcollective_metadatas', [ 'action' => 'metadata', 'agent' => null ], [], true) ?>" class="btn btn-info"><i class="glyphicon glyphicon-chevron-left"></i><?= $this->translate('Back') ?></a>
	</div>

      </div>
      <hr class="col-md-12"/>
      </div>
  <div class="row">
    <div class="col-sm-5">
      <div class="panel panel-default">
	<div class="panel-heading"><span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span><?= $this->translate('Associated Actions')?></div>
	<div class="panel-body">
	  <table class="table table-striped" id="groups">
	    <tbody>
	      <?php foreach($agentList[$agent]->getActions() as $action): ?>
	      <tr id="<?= $agent ?>_tabline">
		<td style="width: 100%">
		  <a class="action-link" href="#"><?= $action->getName() ?></a>
		</td>
	      </tr>
	      <?php endforeach ?>
	    </tbody>
	  </table>

	</div>
      </div>
    </div>
    <div class="col-sm-7" id="legend">
      <div id="help">
	<h1><?= $this->translate('Help') ?></h1>
	<blockquote id="legend_metadata"><p><?= $this->translate("Click on an agent's name to edit its metadata") ?></p>
	</blockquote>
      </div>
      <?php foreach($agentList[$agent]->getActions() as $action): ?>
      <div id="<?= $action->getName() ?>_detail" class="action-detail" style="display: none;">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <button type="button" class="close">&times;</button>
	    <span class="glyphicon glyphicon-th-list"></span>
	    <span class="panel-break"></span>
	    <?= $action->getName(); ?>

	  </div> <!-- end of panel heading -->
	  <div class="panel-body" >
	    <div class="col-md-12">
	    <?php $actionMetadata = $agentDetail->getRelatedActions($action->getName()) ?>
	    <div class="form-group">
	      <label for="actionDesc_<?= $action->getName()?>" class="col-md-3 control-label pull-left"><?= $this->translate('Description')?></label>
	      <div class="col-md-9">
		<?php if($actionMetadata != null): ?>
		<input type="text" class="form-control editable" data-target="#actions" id="actionDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][description]" value="<?= $actionMetadata->getDescription() ?>"></input>				      
		<?php else: ?>
		<input type="text" class="form-control editable" data-target="#actions" placeholder="Description..." name="action[<?= $action->getName() ?>][description]"></input>
		<?php endif ?>
	      </div>
	    </div> <!-- end of form group -->
	    <div class="form-group">
	      <label for="<?= $action->getName() ?>_ihmicon" class="control-label col-md-3 pull-left"><?= $this->translate('Action icon') ?></label>
	      <div class="col-md-9">
		<button id="<?= $action->getName() ?>_ihmicon" class="btn btn-default  editable" data-target="#actions" role="iconpicker" data-iconset="glyphicon" data-placement="top" name="action[<?= $action->getName() ?>][ihmicon]" data-icon="<?= $actionMetadata != null ? $actionMetadata->getIhmIcon() : null ?>"></button>
	      </div>
	    </div> <!-- end of form group ->

	    <div class="form-group">
	      <label for="actionLongDesc_<?= $action->getName()?>" class="col-md-3 control-label pull-left"><?= $this->translate('Long detail')?></label>
	      <div class="col-md-9">
		<?php if($actionMetadata != null): ?>
		<input type="text" class="form-control editable" data-target="#actions" id="actionLongDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][longdesc]" value="<?= $actionMetadata->getLongDesc() ?>"></input>				     
		<?php else: ?>
		<input type="text" class="form-control editable" data-target="#actions" placeholder="Long detail"  name="action[<?= $action->getName() ?>][longdesc]"></input>
		<?php endif ?>
	      </div>
	    </div> <!-- end of form group -->
	    <div class="form-group">
	      <label for="actionShortDesc_<?= $action->getName()?>" class="col-md-3 control-label pull-left"><?= $this->translate('Short detail')?></label>
	      <div class="col-md-9">
		<?php if($actionMetadata != null): ?>
		<input type="text" class="form-control editable" data-target="#actions" id="actionShortDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][shortdesc]" value="<?= $actionMetadata->getShortDesc() ?>"></input>				      
		<?php else: ?>
		<input type="text" class="form-control editable" data-target="#actions" placeholder="Short detail" name="action[<?= $action->getName() ?>][shortdesc]"> </input>
		<?php endif ?>
	      </div>
	    </div> <!-- end of form group -->

	    <div class="form-group">
	  <label for="actionLimitNumber_<?= $action->getName()?>" class="col-md-3 control-label pull-left"><?= $this->translate('Limit Number of hosts')?></label>
	  <div class="col-md-9">
	    <?php if($actionMetadata != null): ?>
	    <input type="text" class="form-control editable" data-target="#actions" id="actionLimitNumber_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][limitnumber]" value="<?= $actionMetadata->getLimitNumber() ?>"></input>				      
	    <?php else: ?>
	    <input type="text" class="form-control editable" data-target="#actions" placeholder="Max number of host impacted" name="action[<?= $action->getName() ?>][limitnumber]"></input>
	    <?php endif ?>
	  </div>
		</div> <!-- end of form group -->
	
	<div class="form-group">
	  <label for="actionLimitHost_<?= $action->getName()?>" class="col-md-3 control-label pull-left"><?= $this->translate('Limit hosts')?></label>
	  <div class="col-md-9">
	    <?php if($actionMetadata != null): ?>
	    <input type="text" class="form-control editable" data-target="#actions" id="actionLimitHost_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][limitHosts]" value="<?= $actionMetadata->getLimitHosts() ?>"></input>				      
	    <?php else: ?>
	    <input type="text" class="form-control editable" data-target="#actions" placeholder="Limit action to hosts ..." name="action[<?= $action->getName() ?>][limitHosts]"></input>
	    <?php endif ?>
	  </div>
	</div> <!-- end of form group -->
	<div class="panel-group" id="<?= $action->getName() ?>_args" role="tablist" aria-multiselectable="true">
	  <?php foreach($action->getInputArguments() as $name => $detail): ?>
	  <?php $argsMetadata = $actionMetadata != null ? $actionMetadata->getArguments($name) : null ?>
	  <div class="panel panel-default">
	    <div class="panel-heading" role="tab" id="<?= $action->getName() ?>_<?= $name ?>">
	      <h4 class="panel-title">
		<a data-toggle="collapse" class="collapsed" data-parent="#<?= $action->getName() ?>_args" href="#<?= $action->getName() ?>_<?= $name ?>_detail" aria-expanded="true" aria-controls="<?= $action->getName() ?>_<?= $name ?>_detail">
		  <?= $this->translate('Argument :') ?> <?= $name ?>
		</a>
		<div class="checkbox pull-right required-arg" >
		  <label>
		    <input type="checkbox" class="editable" data-target="#actions" <?= isset($argsMetadata) && ($argsMetadata->getMandatory() == 1) ? "checked=\"checked\"" : "" ?> name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][mandatory]"><?= $this->translate('Required') ?></input>
		  </label>
		</div> <!-- end of required -->
	      </h4>
	    </div> <!-- end of panel heading -->
	    <div id="<?= $action->getName() ?>_<?= $name ?>_detail" class="panel-collapse collapse" role="tabpanel" aria-labelledby="<?= $action->getName() ?>_<?= $name ?>">
	      <div class="panel-body">
		<div class="form-group col-md-12">
		  <label for="<?= $action->getName()?>_arg_<?= $name ?>" class="col-md-3 control-label pull-left"><?= $this->translate('Description')?></label>
		  <div class="col-md-9">
		    <?php if($argsMetadata != null): ?>
		    <input type="text" class="form-control editable" data-target="#actions" id="<?= $action->getName()?>_arg_<?= $name ?>" name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][description]" value="<?= $argsMetadata->getDescription() ?>"/>
		    <?php else: ?>
		    <input type="text" class="form-control editable" id="<?= $action->getName()?>_arg_<?= $name ?>" data-target="#actions" placeholder="Limit action to hosts ..." name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][description]"/>
		    <?php endif ?>
		  </div>
		</div> <!-- end of form group -->
		<div class="form-group col-md-12">
		  <label for="<?= $action->getName()?>_arg_<?= $name ?>_type" class="col-md-3 control-label pull-left"><?= $this->translate('Type')?></label>
		  <div class="col-md-9">
		    <select id="<?= $action->getName()?>_arg_<?= $name ?>_type" class="form-control chosen-select editable" data-target="#actions" name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][type]" data-rel="chosen">
		      <option value="string">string</option>
		      <option value="list">list</option>
		    </select>
		  </div>
		</div> <!-- end of form group -->
	      
		<div class="form-group col-md-12">
		  <label for="<?= $action->getName()?>_arg_<?= $name ?>_value" class="col-md-3 control-label pull-left"><?= $this->translate('List values')?></label>
		  <div class="col-md-9">
		    <?php if($actionMetadata != null): ?>
		    <input type="text" class="form-control editable" data-target="#actions" id="<?= $action->getName()?>_arg_<?= $name ?>_value" name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][value]" value="<?= $actionMetadata->getLimitHosts() ?>"/>				      
		    <?php else: ?>
		    <input type="text" id="<?= $action->getName()?>_arg_<?= $name ?>_value" class="form-control editable" data-target="#actions" placeholder="Limit action to hosts ..." name="action[<?= $action->getName() ?>][arguments][<?= $name ?>][value]"/>
		    <?php endif ?>
		  </div>
		</div> <!-- end form group -->
	    </div> <!-- end panel body -->
	  </div> <!-- end panel collapse -->
	</div> <!-- end panel -->
          <?php endforeach ?>
	</div> <!-- end pannel-group -->
          </div>
	</div><!-- end of panel body -->
	</div> <!-- end of panel -->
	</div> <!-- end of action detail -->
      <?php endforeach ?>
    </form>
  </div>
    <?php else: ?>
    <div class="col-sm-7">
      <div class="panel panel-default">
	<div class="panel-heading">
	  <span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>
	  <span>
	  <?= $this->translate('Mcollective Agents') ?>
	  </span>
	</div>
	
	<div class="panel-body">
	  <table class="table table-striped" id="groups">
	    <tbody>
	      <?php foreach( $agentList as $agent => $content): ?>
	      <tr id="$agent">
		<td style="width: 100%">
		  <a href="<?= $this->url('mcollective_metadatas', ['agent' => $agent], [], true) ?>"><?= $agent ?></a>
		</td>
	      </tr>
	      <?php endforeach ?>
	    </tbody>
	  </table>
	</div>
      </div>
    </div>
    <div class="col-sm-5" id="legend">
      <div id="help">
	<h1><?= $this->translate('Help') ?></h1>
	<blockquote id="legend_metadata"><p><?= $this->translate("Click on an agent's name to edit its metadata") ?></p>
	</blockquote>
      </div>
    </div>
  </div>
</div>

<?php endif ?>
