<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.metadatas.js'); ?>
<div class="row">
    <div class="col-sm-7">
    <div class="panel panel-default">
    <div class="panel-heading"><span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>Metadata Mcollective</div>
    <div class="panel-body">
<?php if( $agent != null): ?>
	<form class="form-horizontal" action="<?php echo $this->url('mcollective_metadatas_update', ['action' => 'metadataUpdate'], [], true) ?>" method="POST" id="metadataForm">
	  <fieldset class="col-sm-12">
	    <div class="form-group">
	      <label class="control-label" for="selectAgent">Agent</label>
	      <div class="controls row">
		<div class="col-lg-12">
		  <select id="selectAgent" data-placeholder="Selectionnez un Agent..." class="form-control" name="agent" data-rel="chosen">
    <option value="default"></option>
<?php foreach( $agentList as $agentName => $content): ?>
		    <?php if($agentName == $agent) : ?>
		    <?= '<option value="' . $agentName . '" selected >' . $agentName .'</option>'; ?>
		    <?php else : ?>
		    <?= '<option value="' . $agentName . '" >' . $agentName .'</option>'; ?>
		    <?php endif ?>
		    <?php endforeach ?>
                  </select>
                </div>
              </div>
	    </div>
	    <div class="form-group">
	      <div class="controls row">
		<div class="col-lg-12">
		  <div class="input-group">
    <span class="input-group-addon">Description de l'agent</span>
		    <input type="text" class="form-control" id="agentDesc" name="agentDesc" value="<?= $agentDetail->getDescription() ?>"/>
		    <?php if(!empty($agentDetail)): ?>
		    <?php else: ?>
		    <input type="text" class="form-control" placeholder="Description..."/>
		    <?php endif ?>
		    </div>
		</div>
	      </div>
	    </div>
	    <div class="form-group">
	      <label class="control-label" for="selectAgent">Actions</label>
	      <div class="controls row">
		<div class="col-lg-12">
		  <div class="col-sm-11 pull-right">
		  <div class="panel-group" id="actionlist" role="tablist" aria-multiselectable="true">
		  <?php foreach($agentList[$agent]->getActions() as $action): ?>
		  <?php $actionMetadata = $agentDetail->getRelatedActions($action->getName()) ?>
		      <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="head_<?= $action->getName()?>">
			  <h4 class="panel-title">
			    <a data-toggle="collapse" data-parent="#actionlist" href="#<?= $action->getName()?>" aria-expanded="true" aria-controls="collapseOne">			     
			      <?= $action->getName() ?>
			    </a>
			  </h4>
			</div>
			<div id="<?= $action->getName()?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="head_<?= $action->getName()?>">
			  <div class="panel-body">
			    <input type="hidden" id="actionName_<?= $action->getName()?>" name="actionName_<?= $action->getName()?>" value="<?= $action->getName() ?>"/>				      
			    <div class="input-group">
			      <span class="input-group-addon">Description de l'action</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][description]" value="<?= $actionMetadata->getDescription() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Description..." name="action[<?= $action->getName() ?>][description]"/>
			      <?php endif ?>
			    </div>
			    <div class="input-group">
			      <span class="input-group-addon">Long detail</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionLongDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][longdesc]" value="<?= $actionMetadata->getLongDesc() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Long detail"  name="action[<?= $action->getName() ?>][longdesc]"/>
			      <?php endif ?>
			    </div>

			    <div class="input-group">
			      <span class="input-group-addon">Short detail</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionShortDesc_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][shortdesc]" value="<?= $actionMetadata->getShortDesc() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Short detail" name="action[<?= $action->getName() ?>][shortdesc]"/>
			      <?php endif ?>
			    </div>

			    <div class="input-group">
			      <span class="input-group-addon">Ihm Icon</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionIhmIcon_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][ihmicon]" value="<?= $actionMetadata->getIhmIcon() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Ihm glyphicon" name="action[<?= $action->getName() ?>][ihmicon]"/>
			      <?php endif ?>
			    </div>

			    <div class="input-group">
			      <span class="input-group-addon">Limit number</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionLimitNumber_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][limitnumber]" value="<?= $actionMetadata->getLimitNumber() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Max number of host impacted" name="action[<?= $action->getName() ?>][limitnumber]"/>
			      <?php endif ?>
			    </div>

			    <div class="input-group">
			      <span class="input-group-addon">Limit Host</span>
			      <?php if($actionMetadata != null): ?>
			      <input type="text" class="form-control" id="actionLimitHost_<?= $action->getName()?>" name="action[<?= $action->getName() ?>][limitHosts]" value="<?= $actionMetadata->getLimitHosts() ?>"/>				      
			      <?php else: ?>
			      <input type="text" class="form-control" placeholder="Limit action to hosts ..." name="action[<?= $action->getName() ?>][limitHosts]"/>
			      <?php endif ?>
			    </div>
			  </div>
			</div>

		  </div>
		  <?php endforeach ?>
		  </div>
		</div>
	      </div>
		    <div class="form-actions">
	      <button type="submit" class="btn btn-primary" id="mcol-form-submit">Exécuter</button>
	      <button type="reset" class="btn">Annuler</button>
	    </div>
	  </fieldset>
	</form>
	<?php else: ?>
	<h4><?= $choiceText ?></h4>
	    <label class="control-label" for="selectAgent">Agent</label>
	      <div class="controls row">
		<div class="col-lg-12">
		  <select id="selectAgent" data-placeholder="Selectionnez un Agent..." class="form-control" name="agent" data-rel="chosen">
		    <option value="default"></option>
		    <?php foreach( $agentList as $agent => $content): ?>
		    <?= '<option value="' . $agent . '">' . $agent .'</option>'; ?>
		    <?php endforeach ?>
                  </select>
                </div>
              </div>	      
	<?php endif ?>
	
      </div>
    </div>
  </div>
  <div class="col-sm-5" id="legend">
    <?php if (isset($this->error)): ?>
    <ul class="flash">
      <li class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $this->error ?>
      </li>
    </ul>
    <?php else: ?>
    <h1>Infos</h1>
    <blockquote id="legende_mcol"><p>Choisissez l&lsquo;action à réaliser via mcollective dans le menu déroulant. Filtrez ensuite les serveurs ciblés par la commande (accepte les expressions régulières) puis cliquez sur le bouton exécuter.</p>
      <p>Le bouton sera grisé le temps de la validation de la commande. Une notification apparaitra pour indiquer si la commande a été acceptée ou pas.</p>
      <p>Vous pouvez limiter la commande à X serveurs qui répondront au filtre donné.</p>
    </blockquote>
    <!-- <blockquote id="pending_mcol"></blockquote> -->
    <?php endif ?>
  </div>
</div>
<div class="col-sm-12">
  <div class="row" id="resultat_action_mcol"></div>
</div>
