<?php $this->inlineScript()->prependFile($this->basePath() . '/js/kmb.mco.js'); ?>
<div class="row">
  <div class="col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading"><span class="glyphicon glyphicon-cog"></span><span class="panel-break"></span>Actions Mcollective</div>
      <div class="panel-body">
	<form class="form-horizontal" data-async data-target="#resultat_action_mcol" action="<?php echo $this->url('mcollective', ['action' => 'run'], [], true) ?>" method="POST" id="action_mcol">
	  <fieldset class="col-sm-12">
	    <div class="form-group">
	      <label class="control-label" for="selectAgent">Agent</label>
	      <div class="controls row">
		<div class="col-lg-12">
		  <select id="selectAgent" data-placeholder="Selectionnez un Agent..." class="form-control" name="agent" data-rel="chosen" <?php if(is_null($this->environment)):?> disabled <?php endif ?>>
		    <option value="default"></option>
                  </select>
                </div>
              </div>
            </div>
            <div id="form_act_mcol" class="form-group act_mcol">
              <label class="control-label" for="selectAction">Action</label>
              <div class="controls row">
                <div class="col-lg-12">
                  <select id="selectAction" data-placeholder="Selectionnez une Action..." class="form-control selectAction" name="action" data-rel="chosen" <?php if(is_null($this->environment)):?> disabled <?php endif ?>>
		    <option value="default"></option>
                  </select>
                </div>
              </div>
            </div>
            <div id="form_arg_mcol" class="arg_mcol">	      
	    </div>
	    <div class="form-group">
	      <div class="controls row">
		<div class="col-lg-6" id="form_filtre_mcol">
		  <label class="control-label" for="filtre_mcol">Filtre serveurs</label>
		  <input type="text" class="form-control" name="filter" id="filtre_mcol" required <?php if(is_null($this->environment)):?> disabled <?php endif ?>>
		</div>
		<div class="col-lg-6" id="form_limit_mcol">
		  <label class="control-label" for="limit_mcol">Limiter l'action sur X serveurs</label>
		  <input type="text" class="form-control" name="limit" id="limit_mcol" <?php if(is_null($this->environment)):?> disabled <?php endif ?>>
		</div>
	      </div>
	    </div>
	    <div class="form-actions">
	      <button type="submit" class="btn btn-primary<?php if(is_null($this->environment)):?> disabled <?php endif ?>" id="mcol-form-submit">Exécuter</button>
	      <button type="reset" class="btn">Annuler</button>
	    </div>
	  </fieldset>
	</form>
      </div>
    </div>
  </div>
  <div class="col-sm-5" id="legend">
    <?php if (isset($this->error)): ?>
    <ul class="flash">
      <li class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $this->error ?>
      </li>
    </ul>
    <?php else: ?>
    <h1>Légende</h1>
    <blockquote id="legende_mcol"><p>Choisissez l&lsquo;action à réaliser via mcollective dans le menu déroulant. Filtrez ensuite les serveurs ciblés par la commande (accepte les expressions régulières) puis cliquez sur le bouton exécuter.</p>
      <p>Le bouton sera grisé le temps de la validation de la commande. Une notification apparaitra pour indiquer si la commande a été acceptée ou pas.</p>
      <p>Vous pouvez limiter la commande à X serveurs qui répondront au filtre donné.</p>
    </blockquote>
    <?php endif ?>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="row" id="resultat_action_mcol"></div>
  </div>
</div>
